# Generated by Django 5.2.17 on 2026-09-03 17:37

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unit_number', models.CharField(max_length=60)),
                ('vin', models.CharField(blank=True, max_length=32)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('make', models.CharField(blank=True, max_length=100)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('ownership', models.CharField(blank=True, max_length=120)),
                ('specs', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Restricted', 'Restricted'), ('OutOfService', 'Out of service'), ('Retired', 'Retired')], default='Available', max_length=20)),
                ('status_changed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['unit_number'],
            },
        ),
        migrations.CreateModel(
            name='AssetStatusEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('previous_status', models.CharField(blank=True, choices=[('Available', 'Available'), ('Restricted', 'Restricted'), ('OutOfService', 'Out of service'), ('Retired', 'Retired')], max_length=20)),
                ('new_status', models.CharField(choices=[('Available', 'Available'), ('Restricted', 'Restricted'), ('OutOfService', 'Out of service'), ('Retired', 'Retired')], max_length=20)),
                ('reason', models.TextField(max_length=1000)),
                ('source', models.CharField(default='web', max_length=40)),
                ('classification', models.CharField(choices=[('company', 'Company'), ('regulatory', 'Regulatory')], default='company', max_length=20)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='AssetType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(default='vehicle', max_length=40)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Meter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
                ('kind', models.CharField(choices=[('odometer', 'Odometer'), ('engine_hours', 'Engine hours'), ('other', 'Other')], max_length=20)),
                ('unit', models.CharField(max_length=20)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MeterReading',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.DecimalField(decimal_places=3, max_digits=16)),
                ('observed_at', models.DateTimeField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(max_length=40)),
                ('quality', models.CharField(choices=[('accepted', 'Accepted'), ('suspect', 'Suspect'), ('rejected', 'Rejected')], default='accepted', max_length=20)),
                ('provenance', models.JSONField(blank=True, default=dict)),
                ('external_id', models.CharField(blank=True, max_length=160)),
                ('reason', models.TextField(blank=True, max_length=1000)),
            ],
            options={
                'ordering': ['-observed_at', '-received_at'],
            },
        ),
    ]
