# Generated by Django 5.2.17 on 2026-09-03 17:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='assigned_driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_assets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asset',
            name='home_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='core.location'),
        ),
        migrations.AddField(
            model_name='asset',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organization'),
        ),
        migrations.AddField(
            model_name='assetstatusevent',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asset_status_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assetstatusevent',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_events', to='assets.asset'),
        ),
        migrations.AddField(
            model_name='assetstatusevent',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organization'),
        ),
        migrations.AddField(
            model_name='assettype',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organization'),
        ),
        migrations.AddField(
            model_name='asset',
            name='asset_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='assets.assettype'),
        ),
        migrations.AddField(
            model_name='meter',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meters', to='assets.asset'),
        ),
        migrations.AddField(
            model_name='meter',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organization'),
        ),
        migrations.AddField(
            model_name='meterreading',
            name='corrects',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='correction', to='assets.meterreading'),
        ),
        migrations.AddField(
            model_name='meterreading',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='meter_readings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meterreading',
            name='meter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='readings', to='assets.meter'),
        ),
        migrations.AddField(
            model_name='meterreading',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organization'),
        ),
        migrations.AddIndex(
            model_name='assetstatusevent',
            index=models.Index(fields=['organization', 'asset', 'occurred_at'], name='assets_asse_organiz_f131bf_idx'),
        ),
        migrations.AddConstraint(
            model_name='assettype',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='uniq_asset_type_name_org'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['organization', 'status'], name='assets_asse_organiz_ad90f0_idx'),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.UniqueConstraint(fields=('organization', 'unit_number'), name='uniq_asset_unit_org'),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.UniqueConstraint(condition=models.Q(('vin', ''), _negated=True), fields=('organization', 'vin'), name='uniq_asset_vin_org'),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.CheckConstraint(condition=models.Q(('unit_number', ''), _negated=True), name='asset_unit_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='meter',
            constraint=models.UniqueConstraint(fields=('organization', 'asset', 'name'), name='uniq_meter_name_asset'),
        ),
        migrations.AddIndex(
            model_name='meterreading',
            index=models.Index(fields=['organization', 'meter', 'observed_at'], name='assets_mete_organiz_cef80a_idx'),
        ),
        migrations.AddConstraint(
            model_name='meterreading',
            constraint=models.CheckConstraint(condition=models.Q(('value__gte', 0)), name='meter_reading_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='meterreading',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id', ''), _negated=True), fields=('organization', 'meter', 'source', 'external_id'), name='uniq_meter_external_reading'),
        ),
    ]
