# Generated by Django 5.2.17 on 2026-09-06 04:19

import datetime

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models

SECTION_KINDS = {
    "engine": "engine",
    "transmission": "transmission",
    "axle": "axle",
    "emissions": "aftertreatment",
    "auxiliary": "other",
}

# ponytail: legacy equipment serials are free text and contain junk. This list is
# what makes the (org, kind, serial) unique key safe -- without it two sections
# holding "N/A" collapse into one Component representing two physical parts.
PLACEHOLDERS = {
    "N/A", "NA", "NONE", "N\\A", "-", "--", "0", "00", "000",
    "UNKNOWN", "TBD", "SEE PLATE", "ON PLATE", "?",
}

LEGACY_NAMESPACE = uuid.UUID("6b2a1f4c-0d3e-4a1b-9c8d-7e5f4a3b2c1d")


def backfill_specs_serials(apps, schema_editor):
    Asset = apps.get_model("assets", "Asset")
    Component = apps.get_model("assets", "Component")
    Installation = apps.get_model("assets", "ComponentInstallation")
    AssetStatusEvent = apps.get_model("assets", "AssetStatusEvent")

    for asset in Asset.objects.all().iterator():
        equipment = (asset.specs or {}).get("equipment") or {}
        if not isinstance(equipment, dict):
            continue
        for section, kind in SECTION_KINDS.items():
            values = equipment.get(section)
            if not isinstance(values, dict):
                continue
            raw = values.get("serial_number")
            if not isinstance(raw, str):
                continue
            serial = raw.strip().upper()
            if not serial or serial in PLACEHOLDERS or len(serial) < 4:
                if raw.strip():
                    print(
                        f"  skip {asset.unit_number} {section}: "
                        f"{raw.strip()!r} is not a serial"
                    )
                continue
            component, _created = Component.objects.get_or_create(
                organization_id=asset.organization_id,
                kind=kind,
                serial_number=serial,
                defaults={
                    "manufacturer": str(values.get("manufacturer") or "")[:100],
                    "model": str(values.get("model") or "")[:100],
                },
            )
            open_row = Installation.objects.filter(
                component=component, removed_at__isnull=True
            ).select_related("asset").first()
            if open_row is not None:
                print(
                    f"  skip {asset.unit_number} {section}: serial {serial} is "
                    f"already open on {open_row.asset.unit_number}"
                )
                continue
            # ponytail: created_at is only a best guess at when the part went on --
            # source="legacy_specs_backfill" says so. Imported assets can carry an
            # archived_at at or before created_at, which would violate the
            # positive-period constraint and abort the whole migration, so clamp.
            installed_at = asset.created_at
            if asset.archived_at and asset.archived_at <= installed_at:
                installed_at = asset.archived_at - datetime.timedelta(seconds=1)
            row = Installation(
                id=uuid.uuid5(LEGACY_NAMESPACE, f"{asset.pk}:legacy-component:{section}"),
                organization_id=asset.organization_id,
                component=component,
                asset=asset,
                installed_at=installed_at,
                installed_by=None,
                installed_meters=[],
                removed_meters=[],
                source="legacy_specs_backfill",
            )
            if asset.archived_at:
                event = (
                    AssetStatusEvent.objects.filter(asset=asset, new_status="Retired")
                    .order_by("-occurred_at")
                    .first()
                )
                snapshots = []
                if event is not None:
                    snapshots = (event.context or {}).get("final_meter_readings") or []
                row.removed_at = asset.archived_at
                row.removed_meters = snapshots
                row.removal_reason = (
                    "Asset retired" if snapshots else "Asset retired (legacy backfill)"
                )
            row.save()


WRITE_ONCE_SQL = """
CREATE OR REPLACE FUNCTION assets_component_installation_write_once()
RETURNS TRIGGER AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'assets_componentinstallation is append-only'
            USING ERRCODE = '55000';
    END IF;
    IF TG_OP = 'UPDATE'
       AND OLD.removed_at IS NULL
       AND NEW.removed_at IS NOT NULL
       AND ROW(
           NEW.id, NEW.organization_id, NEW.component_id, NEW.asset_id,
           NEW.installed_at, NEW.installed_by_id, NEW.installed_work_order_id,
           NEW.installed_meters, NEW.source, NEW.created_at
       ) IS NOT DISTINCT FROM ROW(
           OLD.id, OLD.organization_id, OLD.component_id, OLD.asset_id,
           OLD.installed_at, OLD.installed_by_id, OLD.installed_work_order_id,
           OLD.installed_meters, OLD.source, OLD.created_at
       ) THEN
        RETURN NEW;
    END IF;
    RAISE EXCEPTION 'assets_componentinstallation is write-once'
        USING ERRCODE = '55000';
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS component_installation_write_once
    ON assets_componentinstallation;
CREATE TRIGGER component_installation_write_once
    BEFORE UPDATE OR DELETE ON assets_componentinstallation
    FOR EACH ROW EXECUTE FUNCTION assets_component_installation_write_once();
"""

WRITE_ONCE_REVERSE = """
DROP TRIGGER IF EXISTS component_installation_write_once
    ON assets_componentinstallation;
DROP FUNCTION IF EXISTS assets_component_installation_write_once();
"""


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_asset_external_identity'),
        ('core', '0011_document_attachment_sensitivity_guard'),
        ('maintenance', '0008_work_order_assignment_identity_snapshots'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('engine', 'Engine'), ('transmission', 'Transmission'), ('reefer_unit', 'Reefer unit'), ('apu', 'APU'), ('axle', 'Axle'), ('aftertreatment', 'Aftertreatment'), ('other', 'Other')], max_length=30)),
                ('serial_number', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(blank=True, max_length=100)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organization')),
            ],
            options={
                'ordering': ['kind', 'serial_number'],
            },
        ),
        migrations.CreateModel(
            name='ComponentInstallation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('installed_at', models.DateTimeField()),
                ('installed_meters', models.JSONField(blank=True, default=list)),
                ('source', models.CharField(default='web', max_length=40)),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
                ('removed_meters', models.JSONField(blank=True, default=list)),
                ('removal_reason', models.TextField(blank=True, max_length=1000)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='component_installations', to='assets.asset')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='installations', to='assets.component')),
                ('installed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='component_installs', to=settings.AUTH_USER_MODEL)),
                ('installed_work_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='component_installs', to='maintenance.workorder')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organization')),
                ('removed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='component_removals', to=settings.AUTH_USER_MODEL)),
                ('removed_work_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='component_removals', to='maintenance.workorder')),
            ],
            options={
                'ordering': ['-installed_at', '-created_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='component',
            index=models.Index(fields=['organization', 'kind'], name='assets_comp_organiz_3ea337_idx'),
        ),
        migrations.AddConstraint(
            model_name='component',
            constraint=models.UniqueConstraint(fields=('organization', 'kind', 'serial_number'), name='uniq_component_kind_serial_org'),
        ),
        migrations.AddConstraint(
            model_name='component',
            constraint=models.CheckConstraint(condition=models.Q(('serial_number', ''), _negated=True), name='component_serial_not_empty'),
        ),
        migrations.AddIndex(
            model_name='componentinstallation',
            index=models.Index(fields=['organization', 'asset', 'installed_at'], name='assets_comp_organiz_095161_idx'),
        ),
        migrations.AddIndex(
            model_name='componentinstallation',
            index=models.Index(fields=['organization', 'component', 'installed_at'], name='assets_comp_organiz_b32056_idx'),
        ),
        migrations.AddConstraint(
            model_name='componentinstallation',
            constraint=models.CheckConstraint(condition=models.Q(('removed_at__isnull', True), ('removed_at__gt', models.F('installed_at')), _connector='OR'), name='component_installation_positive_period'),
        ),
        migrations.AddConstraint(
            model_name='componentinstallation',
            constraint=models.UniqueConstraint(condition=models.Q(('removed_at__isnull', True)), fields=('component',), name='uniq_open_component_installation'),
        ),
        migrations.AddConstraint(
            model_name='componentinstallation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('removal_reason', ''), ('removed_at__isnull', True)), models.Q(('removed_at__isnull', False), models.Q(('removal_reason', ''), _negated=True)), _connector='OR'), name='component_installation_removal_reason'),
        ),
        migrations.RunPython(backfill_specs_serials, migrations.RunPython.noop),
        migrations.RunSQL(sql=WRITE_ONCE_SQL, reverse_sql=WRITE_ONCE_REVERSE),
    ]
