# Generated by Django 5.2.17 on 2026-09-03 17:37

import django.db.models.deletion
import django.utils.timezone
import purchasing.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted'), ('Approved', 'Approved'), ('Sent', 'Sent'), ('PartiallyReceived', 'Partially Received'), ('Received', 'Received'), ('Closed', 'Closed'), ('Cancelled', 'Cancelled')], default='Draft', max_length=24)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('expected_at', models.DateField(blank=True, null=True)),
                ('approval_threshold', models.DecimalField(decimal_places=2, default=purchasing.models.default_approval_threshold, max_digits=14)),
                ('approval_required', models.BooleanField(default=False)),
                ('emergency', models.BooleanField(default=False)),
                ('terms_snapshot', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True, max_length=2000)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_purchase_orders', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_purchase_orders', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organization')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submitted_purchase_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('reason', models.TextField(max_length=1000)),
                ('needed_by', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Converted', 'Converted'), ('Cancelled', 'Cancelled')], default='Submitted', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_purchase_requests', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organization')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_requests', to='inventory.part')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=255)),
                ('vendor_part_number', models.CharField(blank=True, max_length=100)),
                ('quantity_ordered', models.DecimalField(decimal_places=3, max_digits=14)),
                ('unit_cost', models.DecimalField(decimal_places=4, max_digits=14)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organization')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_order_lines', to='inventory.part')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='purchasing.purchaseorder')),
                ('purchase_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_order_lines', to='purchasing.purchaserequest')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=80)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Posted', 'Posted'), ('Reversed', 'Reversed')], default='Draft', max_length=12)),
                ('operation_id', models.UUIDField()),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('packing_slip', models.CharField(blank=True, max_length=120)),
                ('reason', models.CharField(blank=True, max_length=500)),
                ('reversed_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organization')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='purchasing.purchaseorder')),
                ('received_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_receipts', to=settings.AUTH_USER_MODEL)),
                ('reversal_of', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversal', to='purchasing.receipt')),
                ('reversed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversed_purchase_receipts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='ReceiptLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('unit_cost', models.DecimalField(decimal_places=4, max_digits=14)),
                ('bin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipt_lines', to='inventory.bin')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organization')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipt_lines', to='inventory.part')),
                ('purchase_order_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipt_lines', to='purchasing.purchaseorderline')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='purchasing.receipt')),
                ('reversal_of', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversal', to='purchasing.receiptline')),
                ('stock_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipt_line', to='inventory.stocktransaction')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=160)),
                ('contact_name', models.CharField(blank=True, max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('address', models.TextField(blank=True)),
                ('payment_terms', models.CharField(blank=True, max_length=120)),
                ('active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organization')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='purchasing.vendor'),
        ),
        migrations.CreateModel(
            name='VendorPart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor_part_number', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('unit_cost', models.DecimalField(decimal_places=4, max_digits=14)),
                ('lead_time_days', models.PositiveIntegerField(blank=True, null=True)),
                ('preferred', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organization')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendor_parts', to='inventory.part')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parts', to='purchasing.vendor')),
            ],
            options={
                'ordering': ['vendor__name', 'vendor_part_number'],
            },
        ),
        migrations.AddConstraint(
            model_name='purchaserequest',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='purchase_request_qty_positive'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorderline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_ordered__gt', 0)), name='purchase_order_line_qty_positive'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorderline',
            constraint=models.CheckConstraint(condition=models.Q(('unit_cost__gte', 0)), name='purchase_order_line_cost_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='receipt',
            constraint=models.UniqueConstraint(fields=('organization', 'operation_id'), name='uniq_receipt_operation_org'),
        ),
        migrations.AddConstraint(
            model_name='receipt',
            constraint=models.UniqueConstraint(fields=('organization', 'number'), name='uniq_receipt_number_org'),
        ),
        migrations.AddConstraint(
            model_name='receiptline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity', 0), _negated=True), name='receipt_line_qty_nonzero'),
        ),
        migrations.AddConstraint(
            model_name='vendor',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='uniq_vendor_code_org'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorder',
            constraint=models.UniqueConstraint(fields=('organization', 'number'), name='uniq_purchase_order_number_org'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorder',
            constraint=models.CheckConstraint(condition=models.Q(('approval_threshold__gte', 0)), name='purchase_order_threshold_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='vendorpart',
            constraint=models.UniqueConstraint(fields=('organization', 'vendor', 'vendor_part_number'), name='uniq_vendor_part_number_org'),
        ),
        migrations.AddConstraint(
            model_name='vendorpart',
            constraint=models.CheckConstraint(condition=models.Q(('unit_cost__gte', 0)), name='vendor_part_cost_nonnegative'),
        ),
    ]
