# Generated by Django 5.2.17 on 2026-09-03 17:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('provider', models.CharField(default='autopi', max_length=40)),
                ('vendor', models.CharField(default='AutoPi', max_length=80)),
                ('model', models.CharField(blank=True, max_length=120)),
                ('serial_number', models.CharField(max_length=160)),
                ('external_id', models.CharField(max_length=160)),
                ('status', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled')], default='active', max_length=20)),
                ('token_prefix', models.CharField(max_length=12)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('message_count', models.PositiveBigIntegerField(default=0)),
                ('duplicate_count', models.PositiveBigIntegerField(default=0)),
                ('rejected_count', models.PositiveBigIntegerField(default=0)),
                ('quarantined_count', models.PositiveBigIntegerField(default=0)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organization')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceAssetAssociation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('effective_from', models.DateTimeField()),
                ('effective_to', models.DateTimeField(blank=True, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='device_associations', to='assets.asset')),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='device_associations', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='associations', to='integrations.device')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organization')),
            ],
            options={
                'ordering': ['-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='TelematicsMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=40)),
                ('schema_version', models.CharField(max_length=20)),
                ('message_id', models.CharField(blank=True, max_length=160)),
                ('canonical_hash', models.CharField(max_length=64)),
                ('message_type', models.CharField(max_length=40)),
                ('observed_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField()),
                ('sequence', models.BigIntegerField(blank=True, null=True)),
                ('raw_payload', models.JSONField()),
                ('status', models.CharField(choices=[('accepted', 'Accepted'), ('quarantined', 'Quarantined'), ('rejected', 'Rejected')], max_length=20)),
                ('rejection_reason', models.CharField(blank=True, max_length=500)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='integrations.device')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='telematics_messages', to='core.organization')),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='NormalizedTelematicsEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('meter', 'Meter'), ('diagnostic', 'Diagnostic'), ('status', 'Status')], max_length=20)),
                ('signal', models.CharField(max_length=80)),
                ('value', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('observed_at', models.DateTimeField()),
                ('quality', models.CharField(choices=[('accepted', 'Accepted'), ('suspect', 'Suspect'), ('rejected', 'Rejected')], max_length=20)),
                ('reason', models.CharField(blank=True, max_length=500)),
                ('normalized_payload', models.JSONField(default=dict)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='telematics_events', to='assets.asset')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='normalized_events', to='integrations.device')),
                ('meter_reading', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='telematics_events', to='assets.meterreading')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='normalized_telematics_events', to='core.organization')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='normalized_events', to='integrations.telematicsmessage')),
            ],
            options={
                'ordering': ['-observed_at', 'signal'],
            },
        ),
        migrations.AddConstraint(
            model_name='device',
            constraint=models.UniqueConstraint(fields=('organization', 'provider', 'serial_number'), name='uniq_device_provider_serial_org'),
        ),
        migrations.AddConstraint(
            model_name='device',
            constraint=models.UniqueConstraint(fields=('organization', 'external_id'), name='uniq_device_external_id_org'),
        ),
        migrations.AddConstraint(
            model_name='deviceassetassociation',
            constraint=models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gt', models.F('effective_from')), _connector='OR'), name='device_association_positive_period'),
        ),
        migrations.AddConstraint(
            model_name='deviceassetassociation',
            constraint=models.UniqueConstraint(condition=models.Q(('effective_to__isnull', True)), fields=('device',), name='uniq_open_device_association'),
        ),
        migrations.AddIndex(
            model_name='telematicsmessage',
            index=models.Index(fields=['organization', 'status', 'received_at'], name='integration_organiz_231bf0_idx'),
        ),
        migrations.AddIndex(
            model_name='telematicsmessage',
            index=models.Index(fields=['device', 'observed_at'], name='integration_device__0093b0_idx'),
        ),
        migrations.AddConstraint(
            model_name='telematicsmessage',
            constraint=models.UniqueConstraint(condition=models.Q(('message_id', ''), _negated=True), fields=('device', 'message_id'), name='uniq_device_message_id'),
        ),
        migrations.AddConstraint(
            model_name='telematicsmessage',
            constraint=models.UniqueConstraint(fields=('device', 'canonical_hash'), name='uniq_device_canonical_message'),
        ),
        migrations.AddIndex(
            model_name='normalizedtelematicsevent',
            index=models.Index(fields=['organization', 'quality', 'observed_at'], name='integration_organiz_51240e_idx'),
        ),
        migrations.AddConstraint(
            model_name='normalizedtelematicsevent',
            constraint=models.UniqueConstraint(fields=('message', 'kind', 'signal'), name='uniq_normalized_signal_message'),
        ),
    ]
