# Generated by Django 5.2.17 on 2026-09-06 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_components'),
        ('maintenance', '0008_work_order_assignment_identity_snapshots'),
    ]

    operations = [
        migrations.AddField(
            model_name='workordertask',
            name='component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='work_order_tasks', to='assets.component'),
        ),
    ]
