# Generated by Django 5.2.17 on 2026-09-03 17:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('maintenance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(blank=True, max_length=160)),
                ('active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organization')),
            ],
            options={
                'ordering': ['warehouse__code', 'code'],
            },
        ),
        migrations.CreateModel(
            name='InventoryCount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Posted', 'Posted')], default='Draft', max_length=20)),
                ('operation_id', models.UUIDField()),
                ('reason', models.CharField(max_length=500)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_inventory_counts', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organization')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='posted_inventory_counts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=80)),
                ('name', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('manufacturer', models.CharField(blank=True, max_length=120)),
                ('manufacturer_number', models.CharField(blank=True, max_length=120)),
                ('unit_of_measure', models.CharField(default='each', max_length=30)),
                ('barcode', models.CharField(blank=True, max_length=120)),
                ('default_unit_cost', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organization')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='PartCrossReference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('ALTERNATE', 'Alternate'), ('MANUFACTURER', 'Manufacturer'), ('VENDOR', 'Vendor'), ('BARCODE', 'Barcode')], default='ALTERNATE', max_length=20)),
                ('value', models.CharField(max_length=120)),
                ('value_normalized', models.CharField(editable=False, max_length=120)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organization')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cross_references', to='inventory.part')),
            ],
            options={
                'ordering': ['value_normalized'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('issued_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('released_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Active', 'Active'), ('PartiallyIssued', 'Partially issued'), ('Fulfilled', 'Fulfilled'), ('Released', 'Released'), ('Expired', 'Expired')], default='Active', max_length=24)),
                ('operation_id', models.UUIDField()),
                ('reason', models.CharField(blank=True, max_length=500)),
                ('bin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='inventory.bin')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_reservations', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organization')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='inventory.part')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='part_reservations', to='maintenance.workorder')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockBalance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity_on_hand', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('quantity_reserved', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('bin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balances', to='inventory.bin')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organization')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balances', to='inventory.part')),
            ],
        ),
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('RECEIPT', 'Receipt'), ('ISSUE', 'Issue'), ('RETURN', 'Return'), ('ADJUSTMENT', 'Adjustment'), ('COUNT_ADJUSTMENT', 'Count adjustment'), ('REVERSAL', 'Reversal')], max_length=24)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('unit_cost', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('total_cost', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('reference_type', models.CharField(blank=True, max_length=50)),
                ('reference_id', models.CharField(blank=True, max_length=80)),
                ('reason', models.CharField(blank=True, max_length=500)),
                ('operation_id', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_transactions', to=settings.AUTH_USER_MODEL)),
                ('bin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='inventory.bin')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_transactions', to='core.organization')),
                ('original_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compensating_transactions', to='inventory.stocktransaction')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='inventory.part')),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='inventory.reservation')),
                ('work_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_transactions', to='maintenance.workorder')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryCountLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expected_quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('counted_quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('variance', models.DecimalField(decimal_places=3, max_digits=14)),
                ('bin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='count_lines', to='inventory.bin')),
                ('inventory_count', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='inventory.inventorycount')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organization')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='count_lines', to='inventory.part')),
                ('adjustment_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='count_line', to='inventory.stocktransaction')),
            ],
            options={
                'ordering': ['bin__code', 'part__number'],
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=160)),
                ('active', models.BooleanField(default=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warehouses', to='core.location')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organization')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='inventorycount',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_counts', to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='bin',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bins', to='inventory.warehouse'),
        ),
        migrations.AddConstraint(
            model_name='part',
            constraint=models.UniqueConstraint(fields=('organization', 'number'), name='uniq_part_number_org'),
        ),
        migrations.AddConstraint(
            model_name='part',
            constraint=models.UniqueConstraint(condition=models.Q(('barcode', ''), _negated=True), fields=('organization', 'barcode'), name='uniq_part_barcode_org'),
        ),
        migrations.AddConstraint(
            model_name='part',
            constraint=models.CheckConstraint(condition=models.Q(('default_unit_cost__gte', 0)), name='part_default_cost_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='partcrossreference',
            constraint=models.UniqueConstraint(fields=('organization', 'value_normalized'), name='uniq_part_cross_ref_org'),
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.UniqueConstraint(fields=('organization', 'operation_id'), name='uniq_reservation_operation'),
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.CheckConstraint(condition=models.Q(('requested_quantity__gt', 0)), name='reservation_requested_positive'),
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.CheckConstraint(condition=models.Q(('issued_quantity__gte', 0)), name='reservation_issued_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.CheckConstraint(condition=models.Q(('released_quantity__gte', 0)), name='reservation_released_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='stockbalance',
            constraint=models.UniqueConstraint(fields=('part', 'bin'), name='uniq_stock_balance_part_bin'),
        ),
        migrations.AddConstraint(
            model_name='stockbalance',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_on_hand__gte', 0)), name='stock_on_hand_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='stockbalance',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_reserved__gte', 0)), name='stock_reserved_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='stockbalance',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_reserved__lte', models.F('quantity_on_hand'))), name='stock_reserved_lte_on_hand'),
        ),
        migrations.AddIndex(
            model_name='stocktransaction',
            index=models.Index(fields=['organization', 'part', 'bin', 'created_at'], name='inventory_s_organiz_992d79_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransaction',
            index=models.Index(fields=['organization', 'work_order', 'created_at'], name='inventory_s_organiz_8df697_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransaction',
            index=models.Index(fields=['reference_type', 'reference_id'], name='inventory_s_referen_e50b9e_idx'),
        ),
        migrations.AddConstraint(
            model_name='stocktransaction',
            constraint=models.UniqueConstraint(fields=('organization', 'operation_id'), name='uniq_stock_transaction_operation'),
        ),
        migrations.AddConstraint(
            model_name='stocktransaction',
            constraint=models.CheckConstraint(condition=models.Q(('quantity', 0), _negated=True), name='stock_tx_quantity_nonzero'),
        ),
        migrations.AddConstraint(
            model_name='stocktransaction',
            constraint=models.CheckConstraint(condition=models.Q(('unit_cost__gte', 0)), name='stock_tx_cost_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='inventorycountline',
            constraint=models.UniqueConstraint(fields=('inventory_count', 'part', 'bin'), name='uniq_count_line_part_bin'),
        ),
        migrations.AddConstraint(
            model_name='inventorycountline',
            constraint=models.CheckConstraint(condition=models.Q(('expected_quantity__gte', 0)), name='count_expected_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='inventorycountline',
            constraint=models.CheckConstraint(condition=models.Q(('counted_quantity__gte', 0)), name='counted_quantity_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='warehouse',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='uniq_warehouse_code_org'),
        ),
        migrations.AddConstraint(
            model_name='inventorycount',
            constraint=models.UniqueConstraint(fields=('organization', 'operation_id'), name='uniq_inventory_count_operation'),
        ),
        migrations.AddConstraint(
            model_name='bin',
            constraint=models.UniqueConstraint(fields=('warehouse', 'code'), name='uniq_bin_code_warehouse'),
        ),
    ]
