# Generated by Django 5.2.17 on 2026-09-03 18:25

import django.db.models.deletion
import inventory.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_platform_guards'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorycount',
            name='approval_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inventorycount',
            name='approval_threshold',
            field=models.DecimalField(decimal_places=2, default=inventory.models.default_count_variance_approval_threshold, max_digits=14),
        ),
        migrations.AddField(
            model_name='inventorycount',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventorycount',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_inventory_counts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventorycount',
            name='total_variance_value',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='inventorycount',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('PendingApproval', 'Pending approval'), ('Posted', 'Posted')], default='Draft', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='inventorycount',
            constraint=models.CheckConstraint(condition=models.Q(('total_variance_value__gte', 0)), name='inventory_count_variance_value_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='inventorycount',
            constraint=models.CheckConstraint(condition=models.Q(('approval_threshold__gte', 0)), name='inventory_count_approval_threshold_nonnegative'),
        ),
    ]
