# Generated by Django 5.2.17 on 2026-09-03 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_platform_guards'),
        ('inventory', '0002_inventorycount_approval_required_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorycountline',
            name='unit_cost_snapshot',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
        migrations.AddConstraint(
            model_name='inventorycountline',
            constraint=models.CheckConstraint(condition=models.Q(('unit_cost_snapshot__gte', 0)), name='count_line_unit_cost_nonnegative'),
        ),
    ]
