# Generated by Django 5.2.17 on 2026-09-04

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


DOCUMENT_HISTORY_GUARDS_SQL = r"""
CREATE OR REPLACE FUNCTION fleetline_guard_document_delete()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    RAISE EXCEPTION 'core_document records cannot be deleted' USING ERRCODE = '55000';
END;
$$;

CREATE TRIGGER core_document_no_delete
BEFORE DELETE ON core_document
FOR EACH ROW EXECUTE FUNCTION fleetline_guard_document_delete();

CREATE OR REPLACE FUNCTION fleetline_document_page_search_vector()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.search_vector := to_tsvector('english', COALESCE(NEW.text, ''));
    RETURN NEW;
END;
$$;

CREATE TRIGGER core_document_page_search_vector
BEFORE INSERT OR UPDATE OF text ON core_documentpage
FOR EACH ROW EXECUTE FUNCTION fleetline_document_page_search_vector();

CREATE OR REPLACE FUNCTION fleetline_guard_document_page_mutation()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    RAISE EXCEPTION 'core_documentpage is append-only' USING ERRCODE = '55000';
END;
$$;

CREATE TRIGGER core_document_page_immutable
BEFORE UPDATE OR DELETE ON core_documentpage
FOR EACH ROW EXECUTE FUNCTION fleetline_guard_document_page_mutation();
"""

DOCUMENT_HISTORY_GUARDS_REVERSE_SQL = r"""
DROP TRIGGER IF EXISTS core_document_page_immutable ON core_documentpage;
DROP FUNCTION IF EXISTS fleetline_guard_document_page_mutation();
DROP TRIGGER IF EXISTS core_document_page_search_vector ON core_documentpage;
DROP FUNCTION IF EXISTS fleetline_document_page_search_vector();
DROP TRIGGER IF EXISTS core_document_no_delete ON core_document;
DROP FUNCTION IF EXISTS fleetline_guard_document_delete();
"""


class Migration(migrations.Migration):
    dependencies = [
        ("assets", "0003_asset_external_identity"),
        ("core", "0006_allow_staged_attachment_expiry"),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("category", models.CharField(max_length=80)),
                ("manufacturer", models.CharField(blank=True, max_length=120)),
                ("model", models.CharField(blank=True, max_length=120)),
                ("engine_type", models.CharField(blank=True, max_length=120)),
                ("revision", models.CharField(blank=True, max_length=120)),
                ("source", models.CharField(blank=True, max_length=255)),
                ("license", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("quarantined", "Quarantined"),
                            ("queued", "Queued"),
                            ("processing", "Processing"),
                            ("indexed", "Indexed"),
                            ("ocr_unavailable", "OCR unavailable"),
                            ("needs_review", "Needs review"),
                            ("failed", "Failed"),
                        ],
                        default="quarantined",
                        max_length=24,
                    ),
                ),
                ("processing_detail", models.CharField(blank=True, max_length=1000)),
                ("security_review_reference", models.CharField(blank=True, max_length=255)),
                ("security_review_note", models.CharField(blank=True, max_length=1000)),
                ("security_reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documents",
                        to="assets.asset",
                    ),
                ),
                (
                    "attachment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="technical_document",
                        to="core.attachment",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="core.organization"),
                ),
                (
                    "security_reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reviewed_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "supersedes",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="superseded_by",
                        to="core.document",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DocumentApplicability",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("make", models.CharField(blank=True, max_length=100)),
                ("model", models.CharField(blank=True, max_length=100)),
                ("engine_type", models.CharField(blank=True, max_length=120)),
                (
                    "asset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="document_applicability",
                        to="assets.asset",
                    ),
                ),
                (
                    "asset_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="document_applicability",
                        to="assets.assettype",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="applicability",
                        to="core.document",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="core.organization"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DocumentPage",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("page_number", models.PositiveIntegerField()),
                ("text", models.TextField()),
                (
                    "extraction_method",
                    models.CharField(
                        choices=[("embedded", "Embedded PDF text"), ("ocr", "OCR")], max_length=16
                    ),
                ),
                ("confidence", models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ("provenance", models.JSONField(blank=True, default=dict)),
                ("search_vector", django.contrib.postgres.search.SearchVectorField(editable=False, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pages",
                        to="core.document",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="core.organization"),
                ),
            ],
            options={"ordering": ["page_number"]},
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(fields=["organization", "status"], name="core_docume_organiz_22d654_idx"),
        ),
        migrations.AddIndex(
            model_name="documentapplicability",
            index=models.Index(fields=["organization", "asset"], name="core_docume_organiz_f19bb0_idx"),
        ),
        migrations.AddConstraint(
            model_name="documentapplicability",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(("asset__isnull", False))
                    | models.Q(("asset_type__isnull", False))
                    | ~models.Q(("make", ""))
                    | ~models.Q(("model", ""))
                    | ~models.Q(("engine_type", ""))
                ),
                name="document_applicability_target",
            ),
        ),
        migrations.AddIndex(
            model_name="documentpage",
            index=models.Index(
                fields=["organization", "document", "page_number"], name="core_docume_organiz_c0ce76_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="documentpage",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="document_page_search_gin"
            ),
        ),
        migrations.AddConstraint(
            model_name="documentpage",
            constraint=models.UniqueConstraint(fields=("document", "page_number"), name="uniq_document_page"),
        ),
        migrations.AddConstraint(
            model_name="documentpage",
            constraint=models.CheckConstraint(
                condition=models.Q(("page_number__gte", 1)), name="document_page_positive"
            ),
        ),
        migrations.RunSQL(DOCUMENT_HISTORY_GUARDS_SQL, DOCUMENT_HISTORY_GUARDS_REVERSE_SQL),
    ]
